site: Mig Salazar
title: Mig Salazar
author: Mig Salazar
url: https://migsalazar.mx
description: >-
  Debugging stories, coding, hacking and nonsense content
repo: migsalazar/migsalazar.github.io
googlewebfonts: Fira+Code:wght@400;500;700
lang: es-MX
data-theme: dark # default theme "dark" | "light"
# timezone: Rome

# baseurl: ""
permalink: pretty
# permalink: /:year/:month/:day/:title/

twitter:
  username: migsalazar_

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# pigments: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-gist

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


